//! Privacy-safe security event schemas.
//!
//! These events intentionally avoid passwords, credential values, vault item
//! names, browsing history, URLs beyond coarse origin hashes supplied by
//! callers, and decrypted vault content.

use serde::{Deserialize, Serialize};
use time::OffsetDateTime;
use uuid::Uuid;

/// Privacy-safe security event.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PrivacySafeSecurityEvent {
    /// Event identifier.
    pub event_id: Uuid,
    /// Timestamp generated by the component that observed the event.
    pub observed_at: OffsetDateTime,
    /// Component that emitted the event.
    pub component: SecurityComponent,
    /// Event kind.
    pub kind: SecurityEventKind,
    /// Severity.
    pub severity: SecuritySeverity,
    /// Optional device UUID.
    pub device_id: Option<Uuid>,
    /// Optional session UUID.
    pub session_id: Option<Uuid>,
}

/// Component that emitted a security event.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum SecurityComponent {
    /// Desktop runtime.
    Desktop,
    /// Browser extension.
    Extension,
    /// Native messaging host.
    NativeMessagingHost,
    /// Backend API.
    Backend,
}

/// Privacy-safe event kind.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum SecurityEventKind {
    /// Failed unlock attempt.
    FailedUnlock,
    /// IPC replay rejected.
    IpcReplayRejected,
    /// IPC validation failure.
    IpcValidationFailure,
    /// Vault corruption detected.
    VaultCorruptionDetected,
    /// Tamper event detected.
    TamperDetected,
    /// Rate limit enforced.
    RateLimitEnforced,
}

/// Security event severity.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "kebab-case")]
pub enum SecuritySeverity {
    /// Informational event.
    Info,
    /// Suspicious event.
    Warning,
    /// High-signal security event.
    High,
    /// Critical security event.
    Critical,
}

/// In-memory tamper event pipeline for local runtime validation.
#[derive(Debug, Default)]
pub struct TamperEventPipeline {
    events: Vec<PrivacySafeSecurityEvent>,
}

impl TamperEventPipeline {
    /// Creates an empty event pipeline.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Emits an event.
    pub fn emit(&mut self, event: PrivacySafeSecurityEvent) {
        self.events.push(event);
    }

    /// Returns emitted events.
    #[must_use]
    pub fn events(&self) -> &[PrivacySafeSecurityEvent] {
        &self.events
    }
}
